(() => {
  'use strict';

  const course = (id, title, image, teacher, summary, date, price, modality, certificate, tags) => ({
    id, title, image, teacher, summary, date, price, modality, certificate, tags
  });

  window.IMFRA_EXPERIENCE_DATA = Object.freeze({
    brand: {
      name: 'IMFRA Desarrollo',
      assistant: 'Guía IMFRA',
      whatsapp: '522382196286',
      generalWhatsapp: '5212225245127',
      privacyUrl: 'privacidad.html'
    },

    questions: [
      {
        id: 'profile', dimension: 'profiles', kicker: 'Sobre ti',
        title: '¿Dónde te encuentras hoy en el mundo de la construcción?',
        hint: 'No hay respuestas correctas; queremos recomendarte algo que sí te sirva.',
        options: [
          { value: 'student', icon: '🎓', title: 'Estoy estudiando', detail: 'Arquitectura, ingeniería o una carrera afín' },
          { value: 'graduate', icon: '📐', title: 'Recién egresé', detail: 'Quiero fortalecer mi perfil profesional' },
          { value: 'field', icon: '🦺', title: 'Trabajo en obra', detail: 'Supervisión, residencia o ejecución' },
          { value: 'designer', icon: '🏙️', title: 'Diseño y proyecto', detail: 'Arquitectura, cálculo o representación' },
          { value: 'business', icon: '🏗️', title: 'Tengo un negocio', detail: 'Contratista, despacho o constructora' },
          { value: 'team', icon: '👥', title: 'Capacito a un equipo', detail: 'Busco formación para mi empresa' }
        ]
      },
      {
        id: 'experience', dimension: 'level', kicker: 'Tu experiencia',
        title: '¿Qué tanta experiencia tienes en el tema que buscas?',
        hint: 'Así ajustamos la profundidad de la recomendación.',
        options: [
          { value: 'starting', level: 'inicial', icon: '🌱', title: 'Voy comenzando', detail: 'Necesito una base clara' },
          { value: 'basics', level: 'basico', icon: '📘', title: 'Conozco lo básico', detail: 'Quiero ordenar lo que ya sé' },
          { value: 'practical', level: 'intermedio', icon: '🛠️', title: 'Ya lo aplico', detail: 'Busco mejorar mi práctica' },
          { value: 'specialize', level: 'avanzado', icon: '🏆', title: 'Quiero especializarme', detail: 'Necesito mayor profundidad' }
        ]
      },
      {
        id: 'interest', dimension: 'interests', kicker: 'Tu enfoque',
        title: '¿Qué tema te interesa más en este momento?',
        hint: 'Elige el que tendría mayor impacto en tu siguiente proyecto.',
        options: [
          { value: 'supervision', image: 'assets/cursos/curso-01-supervision.jpg', title: 'Supervisión y residencia' },
          { value: 'costs', image: 'assets/cursos/curso-04-control-financiero.jpg', title: 'Costos y control financiero' },
          { value: 'quantities', image: 'assets/cursos/curso-07-numeros.jpg', title: 'Números generadores' },
          { value: 'contracts', image: 'assets/cursos/curso-02-contratos.jpg', title: 'Contratos y riesgos' },
          { value: 'structures', image: 'assets/cursos/curso-03-trabes.jpg', title: 'Estructuras e infraestructura' },
          { value: 'visualization', image: 'assets/cursos/curso-08-sketchup.jpg', title: 'Modelado y presentación' },
          { value: 'management', image: 'assets/cursos/curso-09-gerencia.jpg', title: 'Gerencia de proyectos' },
          { value: 'landscape', image: 'assets/cursos/curso-10-paisajismo.jpg', title: 'Paisajismo rentable' }
        ]
      },
      {
        id: 'goal', dimension: 'goals', kicker: 'Tu siguiente logro',
        title: '¿Qué te gustaría conseguir con esta capacitación?',
        hint: 'Piensa en el resultado que te haría decir: valió la pena.',
        options: [
          { value: 'job', icon: '💼', title: 'Conseguir una oportunidad', detail: 'Mejorar mi perfil y empleabilidad' },
          { value: 'work', icon: '✅', title: 'Trabajar con más seguridad', detail: 'Tomar mejores decisiones técnicas' },
          { value: 'lead', icon: '📊', title: 'Liderar proyectos', detail: 'Coordinar alcance, tiempo y costo' },
          { value: 'business', icon: '📈', title: 'Hacer crecer mi negocio', detail: 'Cobrar, controlar y vender mejor' },
          { value: 'certificate', icon: '🏅', title: 'Respaldar lo que sé', detail: 'Obtener un certificado digital' },
          { value: 'solve', icon: '🎯', title: 'Resolver un reto actual', detail: 'Aplicarlo de inmediato en una obra' }
        ]
      },
      {
        id: 'need', dimension: 'problems', kicker: 'Tu reto actual',
        title: '¿Qué necesitas fortalecer primero?',
        hint: 'Esto define el ángulo práctico de tu ruta.',
        options: [
          { value: 'start', icon: '🧭', title: 'Saber por dónde empezar', detail: 'Necesito una ruta clara' },
          { value: 'practice', icon: '🧰', title: 'Pasar de teoría a práctica', detail: 'Quiero casos y procedimientos' },
          { value: 'control', icon: '📋', title: 'Controlar mejor la obra', detail: 'Orden, evidencia y seguimiento' },
          { value: 'money', icon: '💰', title: 'Cuidar costos y cobros', detail: 'Presupuesto, avance y rentabilidad' },
          { value: 'risk', icon: '🛡️', title: 'Reducir riesgos', detail: 'Contratos, calidad y prevención' },
          { value: 'present', icon: '✨', title: 'Presentar mejor mis proyectos', detail: 'Comunicación visual y profesional' }
        ]
      },
      {
        id: 'format', dimension: 'formats', kicker: 'Tu forma de aprender',
        title: '¿Qué tipo de contenido te ayuda a aprender mejor?',
        hint: 'Tu estilo también dice mucho de tus fortalezas.',
        options: [
          { value: 'video', icon: '▶️', title: 'Explicaciones visuales', detail: 'Ver y escuchar el proceso' },
          { value: 'cases', icon: '🔎', title: 'Casos reales', detail: 'Entender decisiones de obra' },
          { value: 'guides', icon: '📚', title: 'Guías paso a paso', detail: 'Consultar y repasar' },
          { value: 'tools', icon: '🧮', title: 'Ejercicios y herramientas', detail: 'Aprender haciendo' },
          { value: 'mix', icon: '⚡', title: 'Una combinación', detail: 'Alternar explicación y práctica' }
        ]
      },
      {
        id: 'time', dimension: 'time', kicker: 'Tu ritmo',
        title: '¿Cuánto tiempo podrías dedicar a aprender por semana?',
        hint: 'Una ruta sostenible funciona mejor que una promesa difícil de cumplir.',
        options: [
          { value: 'lt1', icon: '⏳', title: 'Menos de una hora', detail: 'Avances pequeños y concretos' },
          { value: '1-2', icon: '🕐', title: 'Entre 1 y 2 horas', detail: 'Una sesión semanal' },
          { value: '3-5', icon: '📅', title: 'Entre 3 y 5 horas', detail: 'Ritmo constante' },
          { value: '5plus', icon: '🚀', title: 'Más de 5 horas', detail: 'Quiero avanzar a profundidad' }
        ]
      }
    ],

    courses: [
      course('supervision', 'Supervisión Integral de Obra Civil e Industrial', 'assets/cursos/curso-01-supervision.jpg', 'Arq. Luis Roberto Bautista Retama', 'Control técnico, coordinación multidisciplinaria y gestión en campo para asegurar calidad, tiempo y cumplimiento.', '29 de junio', '$750 MXN', 'En vivo · Google Meet', 'Certificado digital con folio y QR', { interests: ['supervision', 'management'], goals: ['work', 'lead', 'solve'], profiles: ['field', 'team', 'business'], problems: ['control', 'risk', 'practice'], levels: ['basico', 'intermedio', 'avanzado'] }),
      course('contracts', 'Contratos en la Construcción', 'assets/cursos/curso-02-contratos.jpg', 'Lic. Margarita López Lara', 'Redacción y revisión de contratos para reducir riesgos, definir responsabilidades y proteger los proyectos.', '22 de junio', '$750 MXN', 'Clase online en vivo', 'Reconocimiento institucional con folio y QR', { interests: ['contracts', 'management'], goals: ['business', 'lead', 'solve'], profiles: ['business', 'team', 'field'], problems: ['risk', 'start', 'control'], levels: ['basico', 'intermedio', 'avanzado'] }),
      course('aashto', 'Trabes AASHTO: Fabricación, Montaje y Control en Puentes', 'assets/cursos/curso-03-trabes.jpg', 'Ing. Jorge Sánchez Hernández', 'Fabricación, montaje y control normativo de trabes AASHTO en puentes, tipos II a V.', '22 de junio', '$750 MXN', 'Curso online', 'Certificado digital con QR', { interests: ['structures', 'supervision'], goals: ['work', 'certificate', 'solve'], profiles: ['field', 'graduate', 'team'], problems: ['practice', 'risk', 'control'], levels: ['intermedio', 'avanzado'] }),
      course('financial-control', 'Control Físico Financiero de Obra', 'assets/cursos/curso-04-control-financiero.jpg', 'Ing. Laura Mariella Hernández Pitalua', 'Seguimiento del avance físico y financiero para detectar desviaciones y tomar decisiones oportunas.', '29 de junio', '$750 MXN', 'En vivo · Clase online', 'Certificado digital con QR', { interests: ['costs', 'management', 'quantities'], goals: ['business', 'lead', 'solve'], profiles: ['field', 'business', 'team'], problems: ['money', 'control', 'practice'], levels: ['basico', 'intermedio', 'avanzado'] }),
      course('resident', 'Residente de Obra', 'assets/cursos/curso-05-residente.jpg', 'Ing. Ángel Ricardo Fisher López', 'Funciones, responsabilidades y control técnico de la residencia de obra en proyectos de construcción.', '29 de junio', '$750 MXN', 'En vivo · Google Meet', 'Certificado digital con QR', { interests: ['supervision', 'management'], goals: ['job', 'work', 'certificate'], profiles: ['student', 'graduate', 'field'], problems: ['start', 'control', 'practice'], levels: ['inicial', 'basico', 'intermedio'] }),
      course('sheets', 'Elaboración de Láminas Arquitectónicas Profesionales', 'assets/cursos/curso-06-laminas.jpg', 'Arq. Alesiram Sotelo Peñuelas', 'De la idea a la presentación final: composición y comunicación visual profesional con Photoshop.', '29 de junio', '$750 MXN', 'Online · Google Meet', 'Certificado digital con QR', { interests: ['visualization'], goals: ['job', 'work', 'business'], profiles: ['student', 'graduate', 'designer'], problems: ['present', 'practice', 'start'], levels: ['inicial', 'basico', 'intermedio'] }),
      course('quantities', 'Elaboración de Números Generadores', 'assets/cursos/curso-07-numeros.jpg', 'Arq. Alesiram Sotelo Peñuelas', 'Cuantificación y control de volúmenes de obra para presupuestos y estimaciones confiables.', '22 de junio', '$750 MXN', 'Clase online en vivo', 'Reconocimiento institucional con folio y QR', { interests: ['quantities', 'costs', 'supervision'], goals: ['job', 'work', 'solve'], profiles: ['student', 'graduate', 'field', 'business'], problems: ['money', 'control', 'practice'], levels: ['inicial', 'basico', 'intermedio'] }),
      course('sketchup', 'SketchUp Profesional', 'assets/cursos/curso-08-sketchup.jpg', 'Arq. Carlos Mauricio Pérez Zepeda', 'Modelado arquitectónico en SketchUp desde cero hasta un nivel intermedio para presentar proyectos.', '29 de junio', '$750 MXN', 'Online · Google Meet', 'Certificado digital con QR', { interests: ['visualization'], goals: ['job', 'work', 'business'], profiles: ['student', 'graduate', 'designer'], problems: ['present', 'practice', 'start'], levels: ['inicial', 'basico', 'intermedio'] }),
      course('management', 'Gerencia de Proyectos en Construcción', 'assets/cursos/curso-09-gerencia.jpg', 'Mtro. Arq. Juan Pablo Hernández García', 'Planeación, ejecución y control de proyectos con herramientas de gestión y liderazgo estratégico.', '22 de junio', '$750 MXN', 'Curso online', 'Certificado digital con QR', { interests: ['management', 'costs', 'supervision'], goals: ['lead', 'business', 'work'], profiles: ['field', 'business', 'team'], problems: ['control', 'money', 'risk'], levels: ['basico', 'intermedio', 'avanzado'] }),
      course('landscape', 'Paisajismo Rentable: Costos, Presupuestos y Precios', 'assets/cursos/curso-10-paisajismo.jpg', 'Arq. Laura Elizabeth Espinoza', 'Costeo, presupuesto y precios estratégicos para convertir proyectos de paisajismo en un negocio rentable.', '06 de julio', '$950 MXN', 'En vivo · Google Meet', 'Certificado digital con QR', { interests: ['landscape', 'costs'], goals: ['business', 'work', 'solve'], profiles: ['designer', 'business', 'graduate'], problems: ['money', 'present', 'practice'], levels: ['basico', 'intermedio'] })
    ],

    conceptGroups: [
      { label: 'Obra y supervisión', items: ['supervision', 'residencia', 'bitacora', 'calidad', 'seguridad', 'as-built', 'cimbra', 'colado', 'curado', 'compactacion', 'excavacion', 'entrega-recepcion', 'epp', 'nivel-freatico'] },
      { label: 'Costos y control', items: ['presupuesto', 'apu', 'generadores', 'estimaciones', 'control-financiero', 'costos-indirectos', 'curva-s', 'fsr', 'escalatoria', 'anticipo', 'iva-obra', 'flujo-efectivo', 'opus-neodata', 'rendimientos', 'retencion'] },
      { label: 'Planeación y gestión', items: ['gerencia', 'ruta-critica', 'alcance', 'riesgos', 'contratos', 'licitacion', 'cambio-orden', 'gantt', 'edt', 'valor-ganado', 'lop', 'adjudicacion', 'precio-alzado', 'precios-unitarios', 'convenio-modificatorio', 'finiquito', 'fianza'] },
      { label: 'Diseño y arquitectura', items: ['arquitectura', 'proyecto-arquitectonico', 'partido', 'programa-arquitectonico', 'memoria-descriptiva', 'memoria-calculo', 'normatividad', 'reglamento', 'licencia', 'uso-suelo', 'autocad', 'revit', 'render', 'sketchup', 'laminas', 'bim'] },
      { label: 'Estructuras y materiales', items: ['ingenieria-civil', 'cimentacion', 'geotecnia', 'topografia', 'concreto', 'acero-refuerzo', 'trabes-aashto', 'carga-viva', 'carga-muerta', 'flexion', 'cortante', 'muro-contencion', 'vigueta-bovedilla', 'postensado', 'prefabricado', 'mamposteria', 'cemento', 'mortero', 'agregados', 'aditivos', 'impermeabilizacion', 'junta-constructiva', 'perfil-estructural', 'soldadura', 'zapata', 'pilote', 'losa', 'columna', 'viga', 'pavimento'] },
      { label: 'Instalaciones', items: ['instalacion-hidraulica', 'instalacion-sanitaria', 'instalacion-electrica', 'instalacion-gas', 'cfe', 'conagua'] },
      { label: 'Acabados y albañilería', items: ['acabados', 'albañileria', 'yesos', 'pisos', 'pintura', 'carpinteria', 'herreria', 'canceleria', 'plafones'] }
    ],

    concepts: {
      'ingenieria-civil': { label: 'Ingeniería civil', aliases: ['ingenieria civil', 'que es ingenieria civil'], definition: 'La ingeniería civil planea, diseña, construye, supervisa y conserva infraestructura y edificaciones. Integra estructuras, geotecnia, hidráulica, materiales, costos, seguridad y gestión para convertir una necesidad en una solución construible y durable.', practical: 'Un proyecto sólido conecta criterios de diseño, información del sitio, normativa, presupuesto, programa y control de calidad; ninguna especialidad debería resolverse de forma aislada.', courses: ['Supervisión Integral', 'Gerencia de Proyectos'] },
      supervision: { label: 'Supervisión de obra', aliases: ['supervision', 'supervision de obra', 'supervisor de obra'], definition: 'La supervisión de obra verifica que los trabajos se ejecuten conforme a planos, especificaciones, contrato, programa, presupuesto, seguridad y calidad.', practical: 'Una buena supervisión deja evidencia: reportes, pruebas, fotografías, minutas, bitácora, controles de avance y seguimiento de no conformidades.', courses: ['Supervisión Integral', 'Residente de Obra'] },
      residencia: { label: 'Residencia de obra', aliases: ['residente', 'residente de obra', 'residencia de obra'], definition: 'La residencia de obra representa la conducción técnica cotidiana de la ejecución. Coordina personal, recursos, contratistas, programa, calidad, seguridad y documentación.', practical: 'El residente debe anticipar restricciones, verificar frentes antes de ejecutar, registrar decisiones y escalar oportunamente cualquier desviación de alcance, costo o plazo.', courses: ['Residente de Obra', 'Supervisión Integral'] },
      bitacora: { label: 'Bitácora de obra', aliases: ['bitacora', 'bitacora de obra', 'nota de bitacora'], definition: 'La bitácora de obra es el registro cronológico de hechos, instrucciones, acuerdos, incidencias y decisiones relevantes durante la ejecución.', practical: 'Una nota útil indica fecha, ubicación, hecho verificable, responsable, instrucción o acuerdo, plazo y evidencia. Debe ser clara, objetiva y congruente con el contrato.', courses: ['Supervisión Integral', 'Residente de Obra'] },
      calidad: { label: 'Control de calidad', aliases: ['control de calidad', 'calidad en obra', 'calidad de obra'], definition: 'El control de calidad compara materiales, procedimientos y resultados contra requisitos definidos en planos, especificaciones, normativa y contrato.', practical: 'Funciona mejor con puntos de inspección, criterios de aceptación, trazabilidad de materiales, pruebas, liberaciones y tratamiento documentado de no conformidades.', courses: ['Supervisión Integral', 'Trabes AASHTO'] },
      seguridad: { label: 'Seguridad en obra', aliases: ['seguridad en obra', 'seguridad construccion', 'accidente en obra', 'riesgo de trabajo'], definition: 'La seguridad en obra identifica peligros, evalúa riesgos y establece controles para proteger a trabajadores, visitantes y entorno.', practical: 'La prioridad es eliminar o controlar el peligro desde la planeación, complementar con procedimientos, capacitación y equipo de protección, y detener actividades ante riesgo inminente.', courses: ['Supervisión Integral', 'Residente de Obra'] },
      presupuesto: { label: 'Presupuesto de obra', aliases: ['presupuesto', 'presupuesto de obra', 'costear una obra'], definition: 'Un presupuesto de obra estima el costo de ejecutar un alcance definido mediante cantidades, precios unitarios, indirectos, financiamiento, utilidad y cargos aplicables.', practical: 'Su confiabilidad depende de planos y alcance claros, catálogo completo, cuantificaciones revisadas, rendimientos realistas, cotizaciones vigentes y supuestos documentados.', courses: ['Control Físico Financiero', 'Números Generadores'] },
      apu: { label: 'Análisis de precios unitarios', aliases: ['apu', 'analisis de precio unitario', 'precio unitario'], definition: 'El análisis de precios unitarios descompone el costo de una unidad de trabajo en materiales, mano de obra, maquinaria, herramienta y rendimientos; después integra cargos indirectos y complementarios según el caso.', practical: 'Antes de reutilizar un APU hay que actualizar precios, cuadrillas, rendimientos, desperdicios, ubicación, condiciones de ejecución y alcance exacto del concepto.', courses: ['Control Físico Financiero', 'Números Generadores'] },
      generadores: { label: 'Números generadores', aliases: ['numero generador', 'numeros generadores', 'generador de obra'], definition: 'Los números generadores documentan cómo se obtuvo una cantidad de obra mediante dimensiones, operaciones, ubicación, croquis y referencias a planos.', practical: 'Deben permitir que otra persona reproduzca la cuantificación. Conviene separar por frente, periodo y concepto, conservar unidades coherentes y vincular evidencia.', courses: ['Elaboración de Números Generadores', 'Control Físico Financiero'] },
      estimaciones: { label: 'Estimaciones de obra', aliases: ['estimacion de obra', 'estimaciones', 'cobro de avance'], definition: 'Una estimación de obra cuantifica y valora trabajos ejecutados y aceptados durante un periodo para tramitar su pago conforme al contrato.', practical: 'Se soporta con generadores, reportes, evidencia, pruebas, autorizaciones, amortizaciones y retenciones. Cobrar avance sin respaldo aumenta el riesgo de rechazo o controversia.', courses: ['Elaboración de Números Generadores', 'Control Físico Financiero'] },
      'control-financiero': { label: 'Control físico-financiero', aliases: ['control fisico financiero', 'avance fisico financiero', 'control financiero de obra'], definition: 'El control físico-financiero compara el avance construido con el gasto, compromisos y cobros para detectar desviaciones y pronosticar el cierre del proyecto.', practical: 'No basta comparar porcentajes globales: conviene revisar por partida, frente y periodo, distinguir costo incurrido, comprometido y pagado, y actualizar el costo por terminar.', courses: ['Control Físico Financiero', 'Gerencia de Proyectos'] },
      gerencia: { label: 'Gerencia de proyectos', aliases: ['gerencia de proyectos', 'gestion de proyectos', 'project management'], definition: 'La gerencia de proyectos coordina alcance, tiempo, costo, calidad, recursos, comunicaciones, riesgos y adquisiciones para alcanzar un objetivo definido.', practical: 'Una línea base clara, responsables visibles, control de cambios, reuniones con acuerdos y decisiones basadas en indicadores evitan que el proyecto se administre solo por urgencias.', courses: ['Gerencia de Proyectos', 'Supervisión Integral'] },
      'ruta-critica': { label: 'Ruta crítica', aliases: ['ruta critica', 'camino critico', 'programa de obra'], definition: 'La ruta crítica es la secuencia de actividades que determina la duración mínima del proyecto; un retraso en una actividad crítica puede mover la fecha final si no se recupera tiempo.', practical: 'Para usarla bien se necesitan relaciones lógicas, duraciones realistas, calendarios, restricciones y actualización con avance real. Un diagrama bonito sin seguimiento no controla la obra.', courses: ['Gerencia de Proyectos', 'Supervisión Integral'] },
      alcance: { label: 'Alcance de proyecto', aliases: ['alcance', 'alcance del proyecto', 'scope'], definition: 'El alcance define qué entregables y trabajos forman parte del proyecto y cuáles quedan fuera. Es la base para programar, presupuestar, contratar y aceptar resultados.', practical: 'Conviene descomponerlo en entregables verificables, criterios de aceptación, límites, interfaces y supuestos; los cambios deben evaluarse antes de autorizarse.', courses: ['Gerencia de Proyectos', 'Contratos en la Construcción'] },
      riesgos: { label: 'Riesgos de proyecto', aliases: ['riesgo', 'riesgos de proyecto', 'matriz de riesgos'], definition: 'Un riesgo es un evento incierto que, si ocurre, afecta objetivos como costo, plazo, seguridad, calidad o reputación.', practical: 'Un registro útil identifica causa, evento, impacto, probabilidad, responsable, respuesta y señal de alerta. Priorizar pocos riesgos accionables es mejor que una lista extensa sin seguimiento.', courses: ['Gerencia de Proyectos', 'Contratos en la Construcción'] },
      contratos: { label: 'Contratos de construcción', aliases: ['contrato', 'contratos', 'contrato de obra', 'contratos de construccion'], definition: 'Un contrato de construcción establece alcance, precio, plazo, responsabilidades, forma de pago, cambios, garantías, entregables, riesgos y mecanismos de controversia.', practical: 'Antes de firmar se deben alinear anexos técnicos, catálogo, programa, criterios de aceptación y procedimiento de cambios. Una cláusula no sustituye revisión legal del caso concreto.', courses: ['Contratos en la Construcción', 'Gerencia de Proyectos'] },
      concreto: { label: 'Concreto', aliases: ['concreto', 'hormigon', 'f c', 'resistencia del concreto'], definition: 'El concreto combina cemento, agua, agregados y, cuando corresponde, aditivos. Su desempeño depende de dosificación, materiales, mezclado, transporte, colocación, compactación, curado y verificación.', practical: 'La resistencia no se confirma por apariencia. Se requiere especificación, control de revenimiento y temperatura, muestreo, curado de especímenes y resultados interpretados por personal competente.', courses: ['Supervisión Integral', 'Trabes AASHTO'] },
      'trabes-aashto': { label: 'Trabes AASHTO', aliases: ['aashto', 'trabes aashto', 'vigas aashto', 'puentes'], definition: 'Las trabes AASHTO son elementos prefabricados y presforzados usados en puentes. Sus tipos y dimensiones responden a claros, cargas, diseño y normativa aplicable.', practical: 'Fabricación, izaje, transporte, apoyos, montaje, tolerancias e inspección requieren procedimientos y responsables especializados; no deben improvisarse con datos genéricos.', courses: ['Trabes AASHTO', 'Supervisión Integral'] },
      bim: { label: 'BIM', aliases: ['bim', 'building information modeling', 'modelado de informacion'], definition: 'BIM es una metodología colaborativa que organiza información del activo mediante modelos y procesos compartidos durante diseño, construcción y operación.', practical: 'Su valor no proviene solo del modelo 3D: requiere objetivos, usos BIM, niveles de información, responsables, estándares de intercambio y un entorno común de datos.', courses: ['SketchUp Profesional', 'Gerencia de Proyectos'] },
      sketchup: { label: 'SketchUp', aliases: ['sketchup', 'modelado 3d', 'modelo 3d'], definition: 'SketchUp es una herramienta de modelado 3D usada para estudiar espacios, comunicar propuestas y producir vistas de proyectos.', practical: 'Un modelo profesional se organiza con grupos, componentes, etiquetas y escenas; modelar todo como geometría suelta vuelve difícil editar, medir y documentar.', courses: ['SketchUp Profesional', 'Láminas Arquitectónicas'] },
      laminas: { label: 'Láminas arquitectónicas', aliases: ['lamina arquitectonica', 'laminas arquitectonicas', 'presentacion arquitectonica', 'panel arquitectonico'], definition: 'Una lámina arquitectónica comunica una propuesta mediante jerarquía visual, planos, diagramas, imágenes y texto en una composición legible.', practical: 'Primero se define el mensaje y el recorrido visual; después se ajustan retícula, escala, contraste, tipografía y consistencia gráfica. Más elementos no siempre comunican mejor.', courses: ['Elaboración de Láminas', 'SketchUp Profesional'] },
      paisajismo: { label: 'Paisajismo rentable', aliases: ['paisajismo', 'presupuesto de paisajismo', 'costos de jardineria'], definition: 'Un proyecto de paisajismo rentable conecta diseño, sitio, especies, materiales, instalación, mantenimiento, merma, logística y margen.', practical: 'Conviene separar costos directos, indirectos y contingencias, definir alcance de mantenimiento, medir cantidades y cotizar por entregables claros en lugar de depender solo de un precio por metro cuadrado.', courses: ['Paisajismo Rentable', 'Control Físico Financiero'] },
      'costos-indirectos': { label: 'Costos indirectos', aliases: ['costo indirecto', 'costos indirectos', 'indirectos de obra'], definition: 'Los costos indirectos son recursos necesarios para ejecutar y administrar la obra que no se asignan de manera directa a una sola unidad de trabajo, como oficina de campo, supervisión, servicios, seguridad y administración central.', practical: 'Deben calcularse para el proyecto y plazo reales; copiar un porcentaje histórico puede ocultar personal, instalaciones, garantías o costos financieros que cambian entre obras.', courses: ['Control Físico Financiero', 'Gerencia de Proyectos'] },
      'curva-s': { label: 'Curva S', aliases: ['curva s', 'curva de avance', 'curva de valor ganado'], definition: 'La curva S representa acumulados de avance, costo o valor a través del tiempo. Permite comparar la línea base con el comportamiento real y visualizar desviaciones.', practical: 'Debe construirse con una estructura de desglose consistente y actualizarse con cortes confiables. Dos porcentajes globales parecidos pueden esconder partidas críticas adelantadas o atrasadas.', courses: ['Control Físico Financiero', 'Gerencia de Proyectos'] },
      licitacion: { label: 'Licitación', aliases: ['licitacion', 'concurso de obra', 'propuesta tecnica economica'], definition: 'Una licitación es un proceso competitivo para seleccionar una propuesta conforme a bases, requisitos técnicos, condiciones económicas y criterios de evaluación.', practical: 'Antes de ofertar conviene crear una matriz de cumplimiento, aclarar el alcance, revisar riesgos contractuales, validar cantidades y documentar todos los supuestos de la propuesta.', courses: ['Contratos en la Construcción', 'Gerencia de Proyectos'] },
      'cambio-orden': { label: 'Orden de cambio', aliases: ['orden de cambio', 'cambio de alcance', 'trabajo extraordinario', 'concepto extraordinario'], definition: 'Una orden de cambio formaliza una modificación de alcance, cantidad, especificación, plazo o costo respecto de la línea base contractual.', practical: 'Antes de ejecutar conviene documentar origen, descripción, planos, impacto en tiempo y costo, responsable de autorizar y ajuste contractual. Trabajar primero y negociar después eleva el riesgo de no cobro.', courses: ['Contratos en la Construcción', 'Control Físico Financiero'] },
      'as-built': { label: 'Planos as-built', aliases: ['as built', 'planos as built', 'planos como construido', 'planos finales de obra'], definition: 'Los planos as-built registran cómo quedó realmente construida la obra, incluyendo cambios aprobados, ubicación final de elementos y datos relevantes para operación y mantenimiento.', practical: 'Se actualizan durante la ejecución, no al final de memoria. Deben apoyarse en levantamientos, notas de cambio y revisiones que permitan rastrear quién autorizó cada modificación.', courses: ['Supervisión Integral', 'Residente de Obra'] },
      cimentacion: { label: 'Cimentación', aliases: ['cimentacion', 'cimientos', 'zapata', 'losa de cimentacion'], definition: 'La cimentación transmite las cargas de la estructura al terreno de forma compatible con su capacidad y deformación admisible. Puede ser superficial o profunda según el proyecto y el suelo.', practical: 'La selección requiere cargas, geometría, nivel freático, estudio geotécnico, entorno y normativa. Una solución usada en la obra vecina no sustituye el análisis del sitio.', courses: ['Supervisión Integral', 'Trabes AASHTO'] },
      geotecnia: { label: 'Geotecnia', aliases: ['geotecnia', 'mecanica de suelos', 'estudio de suelo', 'capacidad portante'], definition: 'La geotecnia estudia el comportamiento del suelo y la roca frente a cargas, excavaciones, agua y cambios constructivos para apoyar decisiones de cimentación y estabilidad.', practical: 'Un estudio útil conecta exploración, muestreo, ensayos, modelo estratigráfico y recomendaciones con el proyecto específico; sus resultados no deben extrapolarse sin criterio.', courses: ['Supervisión Integral', 'Gerencia de Proyectos'] },
      topografia: { label: 'Topografía en obra', aliases: ['topografia', 'levantamiento topografico', 'trazo y nivelacion', 'replanteo'], definition: 'La topografía determina posiciones, niveles, distancias y geometría del terreno y de los elementos construidos. Da soporte al levantamiento, trazo, control y verificación.', practical: 'Conviene establecer bancos y referencias protegidas, verificar cierres, calibración y tolerancias, y conservar archivos y reportes para rastrear cada replanteo.', courses: ['Supervisión Integral', 'Residente de Obra'] },
      'acero-refuerzo': { label: 'Acero de refuerzo', aliases: ['acero de refuerzo', 'varilla', 'armado', 'refuerzo de concreto', 'estribo', 'alambron', 'malla electrosoldada'], definition: 'El acero de refuerzo complementa al concreto para resistir esfuerzos y controlar fisuración según el diseño estructural. Su diámetro, cantidad, separación, anclaje y recubrimiento forman parte del cálculo.', practical: 'En obra se verifican certificados, limpieza, ubicación, traslapes, dobleces, separadores, recubrimiento y estabilidad antes del colado. No se deben modificar barras sin autorización del responsable estructural.', courses: ['Supervisión Integral', 'Trabes AASHTO'] },

      cimbra: { label: 'Cimbra y encofrado', aliases: ['cimbra', 'encofrado', 'cimbra de madera', 'cimbra metalica', 'formaleta'], definition: 'La cimbra es la estructura temporal que da forma al concreto y lo sostiene durante fraguado y endurecimiento. Debe diseñarse para cargas de concreto fresco, vibrado, personal, maniobras y empuje lateral.', practical: 'Antes de colar se verifica alineación, aplomo, nivel, hermeticidad, limpieza, desmoldante, apuntalamientos y recubrimientos. El descimbrado se realiza respetando tiempos y resistencias mínimas.', courses: ['Supervisión Integral', 'Residente de Obra'] },
      colado: { label: 'Colado de concreto', aliases: ['colado', 'colar', 'vaciado de concreto', 'vertido de concreto'], definition: 'El colado es la operación de colocar y compactar concreto fresco en el molde o cimbra, garantizando homogeneidad, cobertura del acero y acabado requerido.', practical: 'Planea revenimiento, temperatura, tiempo de transporte, altura de caída, vibrado por capas, juntas frías y cuadrilla. Un colado improvisado produce segregación, cangrejeras o pérdida de recubrimiento.', courses: ['Supervisión Integral', 'Trabes AASHTO'] },
      curado: { label: 'Curado del concreto', aliases: ['curado', 'curar concreto', 'hidratacion del concreto'], definition: 'El curado mantiene humedad y temperatura adecuadas en el concreto joven para que las reacciones de hidratación continúen y se alcance la resistencia esperada.', practical: 'Puede ser por agua, membranas, mantas húmedas o compuestos. Un concreto sin curado puede perder más del 30% de resistencia potencial y presentar fisuras tempranas.', courses: ['Supervisión Integral', 'Trabes AASHTO'] },
      compactacion: { label: 'Compactación de terracerías', aliases: ['compactacion', 'compactar suelo', 'proctor', 'grado de compactacion', 'terraceria'], definition: 'La compactación reduce vacíos en un suelo para aumentar su resistencia y reducir deformaciones. Se controla con pruebas tipo Proctor o nucleares comparando contra una densidad máxima de laboratorio.', practical: 'Debe considerarse humedad óptima, espesor de capa, número de pasadas, tipo de equipo y verificación por capas. Compactar un espesor mayor al adecuado produce resultados aparentes que fallan en operación.', courses: ['Supervisión Integral', 'Residente de Obra'] },
      excavacion: { label: 'Excavación', aliases: ['excavacion', 'excavar', 'corte en obra', 'excavaciones'], definition: 'La excavación retira material del terreno para alojar cimentaciones, instalaciones u obras subterráneas, controlando estabilidad de taludes, drenaje y colindancias.', practical: 'Antes de excavar se revisa estudio geotécnico, instalaciones ocultas, protección de taludes, extracción de agua, señalización y plan de rescate. La improvisación en taludes profundos es la primera causa de accidentes graves.', courses: ['Supervisión Integral', 'Residente de Obra'] },
      'entrega-recepcion': { label: 'Entrega-recepción de obra', aliases: ['entrega recepcion', 'acta de entrega recepcion', 'recepcion de obra'], definition: 'La entrega-recepción formaliza que la obra concluyó conforme a contrato, planos, especificaciones y pruebas de funcionamiento aceptadas.', practical: 'Debe soportarse en caminata técnica, bitácora, generadores finales, planos as-built, manuales, garantías, pruebas, acta y liberación de reservas. Los pendientes se registran con responsable y fecha, no se omiten.', courses: ['Supervisión Integral', 'Contratos en la Construcción'] },
      epp: { label: 'Equipo de protección personal', aliases: ['epp', 'equipo de proteccion personal', 'proteccion personal en obra', 'casco guantes botas'], definition: 'El EPP protege al trabajador de peligros residuales cuando no es posible eliminar o controlar el riesgo en la fuente. Casco, calzado, lentes, auditivos, arnés, guantes y chalecos deben corresponder a la tarea.', practical: 'El EPP se selecciona por análisis de riesgos, se entrega con capacitación, se inspecciona antes de cada jornada y se reemplaza al perder sus propiedades. No sustituye barreras colectivas ni procedimientos seguros.', courses: ['Supervisión Integral', 'Residente de Obra'] },
      'nivel-freatico': { label: 'Nivel freático', aliases: ['nivel freatico', 'manto freatico', 'agua subterranea', 'napa freatica'], definition: 'El nivel freático es la profundidad a la que el suelo se encuentra saturado de agua. Afecta cimentaciones, excavaciones, muros de contención y durabilidad de materiales enterrados.', practical: 'Cuando hay riesgo de agua se diseña drenaje, achique, impermeabilización, lastre y protección anticorrosiva. Ignorarlo provoca empujes imprevistos, pérdida de capacidad de carga y filtraciones permanentes.', courses: ['Supervisión Integral', 'Trabes AASHTO'] },

      fsr: { label: 'Factor de salario real', aliases: ['fsr', 'factor de salario real', 'calculo del fsr', 'factor del trabajador'], definition: 'El Factor de Salario Real convierte el salario diario nominal en costo real por día trabajado, considerando días no laborables pagados, prestaciones, prima vacacional, aguinaldo, IMSS, INFONAVIT, SAR y riesgo de trabajo.', practical: 'Debe calcularse con tabulador vigente, salarios reales, antigüedad y clase de riesgo correcta; copiar un FSR de otro proyecto genera presupuestos engañosos y pérdidas al pagar la nómina real.', courses: ['Control Físico Financiero', 'Números Generadores'] },
      escalatoria: { label: 'Escalatoria de precios', aliases: ['escalatoria', 'ajuste de precios', 'escalacion', 'formula de ajuste'], definition: 'La escalatoria ajusta precios unitarios cuando los insumos cambian de valor durante la ejecución, con una fórmula que compara índices del periodo contratado contra los del periodo ejecutado.', practical: 'Debe estar prevista en contrato, apoyarse en índices oficiales y aplicarse por partida o insumo relevante. Sin cláusula, los incrementos quedan absorbidos por el contratista o requieren convenio modificatorio.', courses: ['Contratos en la Construcción', 'Control Físico Financiero'] },
      anticipo: { label: 'Anticipo de obra', aliases: ['anticipo', 'anticipo de obra', 'anticipo contractual'], definition: 'El anticipo es un pago inicial del cliente al contratista para iniciar trabajos, comprar materiales o movilizar equipo. Se garantiza con fianza y se amortiza en cada estimación.', practical: 'Define porcentaje, destino del recurso, periodo de amortización y fecha límite para su entrega. Un anticipo sin amortización clara genera descuadres financieros y controversias al cierre.', courses: ['Contratos en la Construcción', 'Control Físico Financiero'] },
      'iva-obra': { label: 'IVA en obra', aliases: ['iva en obra', 'iva construccion', 'tasa iva obra', 'iva estimacion'], definition: 'El IVA en obra se aplica según la naturaleza del contrato, el tipo de cliente y la clasificación de los trabajos. Puede causarse al momento del pago o al expedirse el comprobante.', practical: 'Debe revisarse con el asesor fiscal antes de contratar: contratos a precios unitarios, prestación de servicios, obra pública y obra privada pueden tener tratamientos distintos. Facturar mal el IVA complica cobros y declaraciones.', courses: ['Control Físico Financiero', 'Contratos en la Construcción'] },
      'flujo-efectivo': { label: 'Flujo de efectivo de obra', aliases: ['flujo de efectivo', 'cashflow', 'liquidez de la obra'], definition: 'El flujo de efectivo proyecta ingresos y egresos reales del proyecto en el tiempo, considerando anticipos, estimaciones, retenciones, amortizaciones, pagos a proveedores y nómina.', practical: 'Debe construirse por semana o quincena y compararse contra lo real; un proyecto puede ser rentable en papel y fracasar por falta de liquidez si se descoordinan cobros, pagos y adquisiciones.', courses: ['Control Físico Financiero', 'Gerencia de Proyectos'] },
      'opus-neodata': { label: 'Software de costos (Opus, Neodata)', aliases: ['opus', 'neodata', 'software de costos', 'software de obra', 'programa de presupuestos'], definition: 'Opus, Neodata y herramientas similares integran análisis de precios unitarios, catálogos, matrices, explosión de insumos, generadores y reportes para licitar y controlar obra.', practical: 'El software ordena y acelera, pero no sustituye el criterio: rendimientos irreales, insumos desactualizados o un catálogo mal estructurado producen presupuestos erróneos aunque el software reporte totales correctos.', courses: ['Control Físico Financiero', 'Números Generadores'] },
      rendimientos: { label: 'Rendimientos de obra', aliases: ['rendimiento', 'rendimientos', 'rendimiento de mano de obra', 'rendimiento de equipo'], definition: 'El rendimiento mide cuánta cantidad de trabajo produce una cuadrilla o equipo por unidad de tiempo. Alimenta precios unitarios, programas y asignación de recursos.', practical: 'Debe medirse en campo con bitácora, considerar aprendizaje, condiciones del sitio, interrupciones y clima. Un rendimiento de catálogo copiado sin ajuste suele sobreestimar la capacidad real.', courses: ['Control Físico Financiero', 'Números Generadores'] },
      retencion: { label: 'Retención y fondo de garantía', aliases: ['retencion', 'retencion contractual', 'fondo de garantia', 'retencion por vicios ocultos'], definition: 'La retención descuenta un porcentaje de cada estimación para constituir un fondo que respalda al cliente ante vicios ocultos, correcciones o incumplimientos durante el periodo de garantía.', practical: 'Define porcentaje, condiciones de liberación, posibilidad de sustituir por fianza y plazo. Olvidar la fecha de liberación es una pérdida silenciosa de capital para el contratista.', courses: ['Contratos en la Construcción', 'Control Físico Financiero'] },

      gantt: { label: 'Diagrama de Gantt', aliases: ['gantt', 'diagrama de gantt', 'programa de obra'], definition: 'El diagrama de Gantt representa actividades, duraciones, relaciones y fechas de inicio y fin en una línea de tiempo. Comunica la secuencia del proyecto de manera accesible.', practical: 'Debe apoyarse en una estructura de desglose, duraciones realistas, relaciones lógicas y actualizaciones periódicas. Un Gantt estático sin reporte de avance pierde utilidad como herramienta de control.', courses: ['Gerencia de Proyectos', 'Residente de Obra'] },
      edt: { label: 'EDT / WBS', aliases: ['edt', 'wbs', 'estructura de desglose de trabajo', 'desglose del proyecto'], definition: 'La Estructura de Desglose del Trabajo descompone el proyecto en entregables y paquetes de trabajo manejables, cada uno con alcance, responsable, duración y costo asignables.', practical: 'Una EDT útil es jerárquica, mutuamente excluyente y colectivamente exhaustiva; es base del cronograma, presupuesto, control de avance y asignación de responsabilidades.', courses: ['Gerencia de Proyectos', 'Control Físico Financiero'] },
      'valor-ganado': { label: 'Valor ganado (EVM)', aliases: ['valor ganado', 'evm', 'earned value', 'spi', 'cpi'], definition: 'La gestión del valor ganado integra alcance, tiempo y costo mediante indicadores como SPI (desempeño en cronograma) y CPI (desempeño en costo) para medir dónde está el proyecto respecto al plan.', practical: 'Requiere línea base confiable, reglas claras de medición de avance y cortes periódicos; mal implementado puede dar falsa sensación de control cuando los avances se declaran por juicio en lugar de evidencia.', courses: ['Gerencia de Proyectos', 'Control Físico Financiero'] },
      lop: { label: 'Ley de Obras Públicas', aliases: ['lop', 'ley de obras publicas', 'obra publica', 'loposrm'], definition: 'La Ley de Obras Públicas y Servicios Relacionados con las Mismas (LOPSRM) regula la contratación de obra pública federal: planeación, licitación, contratación, ejecución y recepción.', practical: 'Impone requisitos de inscripción, procedimientos de selección, garantías, modificaciones y responsabilidades. Participar en obra pública sin dominar su reglamento expone a sanciones y rescisiones.', courses: ['Contratos en la Construcción', 'Gerencia de Proyectos'] },
      adjudicacion: { label: 'Adjudicación de contratos', aliases: ['adjudicacion', 'adjudicacion directa', 'invitacion restringida', 'adjudicacion de obra'], definition: 'La adjudicación es el proceso formal por el cual se otorga un contrato: puede ser por licitación pública, invitación a cuando menos tres personas o adjudicación directa, según monto y supuestos legales.', practical: 'Cada vía tiene umbrales y requisitos; documentar la justificación es tan importante como ejecutar el proceso: una adjudicación mal fundamentada puede derivar en observaciones o nulidad.', courses: ['Contratos en la Construcción', 'Gerencia de Proyectos'] },
      'precio-alzado': { label: 'Contrato a precio alzado', aliases: ['precio alzado', 'contrato precio alzado', 'suma alzada'], definition: 'En un contrato a precio alzado el contratista se obliga a entregar la obra completa por una suma fija, asumiendo variaciones de cantidades y precios salvo cambios de alcance autorizados.', practical: 'Exige planos y especificaciones muy claros al momento de contratar; sin esa base, el contratista absorbe sorpresas o el cliente paga convenios modificatorios no previstos.', courses: ['Contratos en la Construcción', 'Gerencia de Proyectos'] },
      'precios-unitarios': { label: 'Contrato a precios unitarios', aliases: ['precios unitarios', 'contrato a precios unitarios', 'pu contrato'], definition: 'En un contrato a precios unitarios se pacta un precio por unidad de cada concepto y se paga la cantidad realmente ejecutada, verificada mediante generadores y estimaciones.', practical: 'Reduce el riesgo de volumetría inexacta pero obliga a controlar generadores, autorizaciones y precios extraordinarios. Requiere disciplina documental mayor que un precio alzado.', courses: ['Contratos en la Construcción', 'Números Generadores'] },
      'convenio-modificatorio': { label: 'Convenio modificatorio', aliases: ['convenio modificatorio', 'adenda', 'modificacion de contrato'], definition: 'El convenio modificatorio formaliza cambios al contrato original en alcance, monto, plazo, especificaciones o condiciones, manteniendo el objeto principal.', practical: 'Debe sustentarse en documentos técnicos, análisis financiero y autorización competente antes de ejecutar los cambios; firmar al final de la obra deja pendientes de cobro y controversias.', courses: ['Contratos en la Construcción', 'Control Físico Financiero'] },
      finiquito: { label: 'Finiquito de obra', aliases: ['finiquito', 'finiquito de obra', 'finiquito contractual'], definition: 'El finiquito cierra formalmente las obligaciones económicas y técnicas del contrato tras la entrega-recepción, liberando saldos, retenciones y garantías conforme a lo acordado.', practical: 'Requiere acta de entrega, generadores finales, pago de estimaciones, liberación de fianzas, respuesta a reclamos y declaración expresa de que no quedan adeudos ni reservas.', courses: ['Contratos en la Construcción', 'Control Físico Financiero'] },
      fianza: { label: 'Fianzas de obra', aliases: ['fianza', 'fianzas', 'fianza de cumplimiento', 'fianza de anticipo', 'fianza de vicios ocultos'], definition: 'Las fianzas garantizan al cliente que el contratista cumplirá las obligaciones contractuales: aplicación del anticipo, ejecución, calidad post-entrega y en algunos casos buen uso de pagos.', practical: 'Deben contratarse con afianzadora autorizada, con montos, plazos y causales ajustadas al contrato. Mantener su vigencia y evitar siniestros requiere comunicación con el cliente y respuesta oportuna.', courses: ['Contratos en la Construcción', 'Gerencia de Proyectos'] },

      arquitectura: { label: 'Arquitectura', aliases: ['arquitectura', 'que es arquitectura', 'diseño arquitectonico'], definition: 'La arquitectura es la disciplina que organiza espacios habitables integrando función, forma, estructura, contexto, normatividad, materiales, confort, sustentabilidad, significado y presupuesto.', practical: 'Un buen proyecto arquitectónico resuelve el programa del usuario, se adapta al sitio y al clima, respeta la normatividad vigente y considera presupuesto y mantenimiento desde el partido inicial.', courses: ['Elaboración de Láminas', 'SketchUp Profesional'] },
      'proyecto-arquitectonico': { label: 'Proyecto arquitectónico', aliases: ['proyecto arquitectonico', 'proyecto ejecutivo arquitectonico', 'proyecto de arquitectura'], definition: 'El proyecto arquitectónico es el conjunto de planos, memorias y especificaciones que define cómo se construirá un edificio: distribución, instalaciones, acabados, criterios estructurales y normatividad.', practical: 'Un proyecto ejecutivo completo evita que decisiones se tomen en obra bajo presión; faltantes se traducen en cambios, extras, retrasos y conflictos con el constructor.', courses: ['Elaboración de Láminas', 'SketchUp Profesional'] },
      partido: { label: 'Partido arquitectónico', aliases: ['partido arquitectonico', 'partido', 'concepto arquitectonico'], definition: 'El partido arquitectónico es la idea rectora del proyecto: la respuesta sintetizada al programa, sitio y objetivos del cliente. Define geometría, zonificación, orientaciones y jerarquías principales.', practical: 'Un buen partido se defiende con diagramas, no solo con imágenes; cuando el partido es claro, cada decisión posterior se evalúa contra él y la propuesta mantiene coherencia.', courses: ['Elaboración de Láminas', 'SketchUp Profesional'] },
      'programa-arquitectonico': { label: 'Programa arquitectónico', aliases: ['programa arquitectonico', 'programa de necesidades', 'programa de areas'], definition: 'El programa arquitectónico lista los espacios requeridos, superficies, usuarios, actividades, mobiliario, relaciones funcionales y requerimientos técnicos de cada ambiente.', practical: 'Construirlo con el cliente evita rediseños: validar superficies, horarios, interacciones y restricciones antes de dibujar un trazo ahorra tiempo y dinero.', courses: ['Elaboración de Láminas', 'Gerencia de Proyectos'] },
      'memoria-descriptiva': { label: 'Memoria descriptiva', aliases: ['memoria descriptiva', 'memoria del proyecto'], definition: 'La memoria descriptiva explica el proyecto en texto: antecedentes, programa, criterios de diseño, materiales, instalaciones, normatividad y referencias que justifican las decisiones.', practical: 'Es la pieza que acompaña los planos ante autoridades, clientes o inversionistas; una memoria confusa deja huecos que después se traducen en observaciones y cambios.', courses: ['Elaboración de Láminas', 'Gerencia de Proyectos'] },
      'memoria-calculo': { label: 'Memoria de cálculo', aliases: ['memoria de calculo', 'memoria estructural', 'calculo estructural'], definition: 'La memoria de cálculo documenta los análisis de ingeniería que respaldan el diseño: cargas, materiales, modelos, resultados y referencias normativas, firmada por el responsable.', practical: 'Es un documento legal y técnico: no puede improvisarse ni copiarse. Pedir siempre memoria firmada y revisar que corresponda a los planos finales evita riesgos estructurales y legales.', courses: ['Supervisión Integral', 'Trabes AASHTO'] },
      normatividad: { label: 'Normatividad de construcción', aliases: ['normatividad', 'normas de construccion', 'nom construccion', 'normativa'], definition: 'La normatividad de construcción agrupa reglamentos, leyes, normas oficiales mexicanas (NOM), normas mexicanas (NMX) y referencias técnicas que definen requisitos mínimos de seguridad, calidad y habitabilidad.', practical: 'Debe revisarse al inicio del proyecto por municipio, estado y materia (estructural, incendios, accesibilidad, instalaciones). Actuar fuera de la normatividad vigente abre riesgos sanitarios, legales y de responsabilidad civil.', courses: ['Contratos en la Construcción', 'Supervisión Integral'] },
      reglamento: { label: 'Reglamento de construcción', aliases: ['reglamento de construccion', 'reglamento municipal', 'reglamento local'], definition: 'El reglamento de construcción es la norma local (municipal o estatal) que define usos de suelo, alturas, áreas libres, estacionamientos, trámites, licencias y responsabilidades técnicas.', practical: 'Cada municipio tiene reglas distintas; aplicar el reglamento del vecino sin revisar el local produce rechazos, multas y pérdida de inversión en proyecto.', courses: ['Contratos en la Construcción', 'Gerencia de Proyectos'] },
      licencia: { label: 'Licencia de construcción', aliases: ['licencia de construccion', 'permiso de obra', 'permiso de construccion'], definition: 'La licencia de construcción es la autorización oficial que permite iniciar una obra conforme al proyecto registrado, el uso de suelo y los pagos correspondientes.', practical: 'Debe tramitarse antes de iniciar la obra con planos, memorias, responsable registrado y comprobantes; iniciar sin licencia expone a clausura, multas y, en algunos casos, demolición.', courses: ['Contratos en la Construcción', 'Gerencia de Proyectos'] },
      'uso-suelo': { label: 'Uso de suelo', aliases: ['uso de suelo', 'uso de suelo compatible', 'certificado de uso de suelo'], definition: 'El uso de suelo es la clasificación que define qué actividades permite un predio según el plan de desarrollo urbano: habitacional, comercial, industrial, mixto, equipamiento o reserva.', practical: 'Antes de comprar o diseñar conviene solicitar constancia o certificado oficial; promesas verbales o mapas no actualizados pueden impedir la operación una vez construido.', courses: ['Contratos en la Construcción', 'Gerencia de Proyectos'] },
      autocad: { label: 'AutoCAD', aliases: ['autocad', 'dibujo en cad', 'planos en cad'], definition: 'AutoCAD es un software de dibujo técnico vectorial muy usado para planos arquitectónicos, estructurales, de instalaciones y detalles constructivos.', practical: 'Para que un plano sea confiable se usan capas estandarizadas, escalas correctas, bloques, cotas vinculadas y presentaciones. Dibujar sobre un archivo heredado sin ordenarlo trae errores difíciles de rastrear.', courses: ['Elaboración de Láminas', 'SketchUp Profesional'] },
      revit: { label: 'Revit y BIM', aliases: ['revit', 'autodesk revit', 'bim modelado'], definition: 'Revit es un software de modelado paramétrico orientado a BIM. Permite integrar arquitectura, estructura e instalaciones en un modelo coordinado del edificio.', practical: 'Requiere protocolos de modelado, niveles de información y revisiones de interferencias. Usarlo como un simple dibujante 3D desperdicia su valor principal: la coordinación entre disciplinas.', courses: ['SketchUp Profesional', 'Gerencia de Proyectos'] },
      render: { label: 'Renders arquitectónicos', aliases: ['render', 'renders', 'imagenes 3d', 'perspectivas'], definition: 'Un render es una imagen fotorrealista obtenida de un modelo 3D que ayuda a comunicar materiales, iluminación y ambientación de un proyecto.', practical: 'El valor del render depende de encuadre, iluminación, materiales reales, personas y entorno, no solo del motor; una imagen bonita de un diseño confuso puede engañar al cliente y abrir reclamos al construir.', courses: ['SketchUp Profesional', 'Elaboración de Láminas'] },
      'carga-viva': { label: 'Carga viva', aliases: ['carga viva', 'cargas vivas', 'cv estructural'], definition: 'La carga viva corresponde al peso variable que soporta una estructura: ocupantes, mobiliario, equipos no fijos, materiales almacenados, nieve o viento según el reglamento aplicable.', practical: 'Los valores se toman del reglamento local y se combinan con cargas muertas y accidentales según el estado límite analizado. Modificar el uso de un espacio puede exceder la carga viva de diseño y requerir revisión estructural.', courses: ['Supervisión Integral', 'Trabes AASHTO'] },
      'carga-muerta': { label: 'Carga muerta', aliases: ['carga muerta', 'cargas muertas', 'cm estructural', 'peso propio'], definition: 'La carga muerta es el peso permanente de la estructura y sus componentes fijos: losas, muros, acabados, instalaciones adosadas y plafones.', practical: 'Cambios aparentemente menores (un piso extra de concreto, un plafón pesado, equipos adosados) pueden incrementar la carga muerta por encima de lo supuesto. Siempre revisar antes de modificar.', courses: ['Supervisión Integral', 'Trabes AASHTO'] },
      flexion: { label: 'Flexión estructural', aliases: ['flexion', 'momento flexionante', 'esfuerzo de flexion'], definition: 'La flexión es el esfuerzo que aparece en elementos sometidos a cargas perpendiculares a su eje longitudinal; produce compresión en una cara y tensión en la opuesta.', practical: 'Vigas, losas y trabes se diseñan para resistir flexión con acero principal en la zona de tensión, estribos para cortante y revisiones de deflexión. Modificar refuerzo sin cálculo compromete la seguridad.', courses: ['Trabes AASHTO', 'Supervisión Integral'] },
      cortante: { label: 'Esfuerzo cortante', aliases: ['cortante', 'esfuerzo cortante', 'fuerza cortante'], definition: 'El cortante es el esfuerzo que tiende a deslizar una sección respecto a la adyacente; es crítico cerca de apoyos y en zonas de carga concentrada.', practical: 'Se controla con estribos, geometría y resistencia del concreto. Una grieta inclinada cerca del apoyo o un estribo mal cerrado son señales de alerta que requieren revisión inmediata.', courses: ['Trabes AASHTO', 'Supervisión Integral'] },
      'muro-contencion': { label: 'Muro de contención', aliases: ['muro de contencion', 'muro de retencion', 'contencion de taludes'], definition: 'Un muro de contención soporta empujes horizontales de suelo o agua para estabilizar diferencias de nivel. Puede ser de gravedad, voladizo, con contrafuertes, anclado o reforzado.', practical: 'Su diseño exige estudio geotécnico, drenaje adecuado, impermeabilización y verificación de vuelco, deslizamiento y capacidad del suelo. Un muro sin drenaje puede fallar aunque el acero sea correcto.', courses: ['Supervisión Integral', 'Trabes AASHTO'] },
      'vigueta-bovedilla': { label: 'Sistema vigueta y bovedilla', aliases: ['vigueta y bovedilla', 'vigueta bovedilla', 'losa aligerada vigueta'], definition: 'El sistema vigueta y bovedilla combina viguetas pretensadas con bovedillas de material ligero y una capa de compresión de concreto para formar losas aligeradas.', practical: 'Requiere separaciones correctas, apuntalamientos temporales, malla electrosoldada en la capa de compresión y colado continuo. Omitir apuntalamientos o reducir la capa compromete la capacidad de la losa.', courses: ['Supervisión Integral', 'Residente de Obra'] },
      postensado: { label: 'Concreto postensado y presforzado', aliases: ['postensado', 'presforzado', 'pretensado', 'concreto postensado'], definition: 'El concreto postensado o presforzado utiliza cables tensionados para introducir compresión que contrarresta parte de las cargas, permitiendo claros mayores y secciones más esbeltas.', practical: 'Fabricación, tendido, tensionado, protección de cables, inyección y pruebas requieren personal certificado y procedimientos auditables. No es un sistema para improvisar en obra.', courses: ['Trabes AASHTO', 'Supervisión Integral'] },
      prefabricado: { label: 'Elementos prefabricados', aliases: ['prefabricado', 'prefabricados', 'elementos prefabricados'], definition: 'Los elementos prefabricados se producen fuera del sitio bajo condiciones controladas y se montan en obra, reduciendo tiempos y aumentando la calidad reproducible.', practical: 'Exige coordinación con planos de taller, ruta de transporte, maniobras, tolerancias de montaje, apoyos y conexiones. Un error de medida en obra se traduce en cortes o rechazos costosos.', courses: ['Trabes AASHTO', 'Supervisión Integral'] },
      mamposteria: { label: 'Mampostería', aliases: ['mamposteria', 'muro de carga', 'muro de block', 'tabique'], definition: 'La mampostería es un sistema estructural o divisorio formado por piezas (block, tabique, piedra) unidas con mortero, que puede ser confinada, reforzada, de piedra o seca.', practical: 'Los muros deben respetar aparejos, refuerzos, dalas, castillos, anclajes y recubrimientos. Omitir castillos o colocar refuerzo insuficiente genera fisuración y falla ante sismos.', courses: ['Supervisión Integral', 'Residente de Obra'] },
      cemento: { label: 'Cemento', aliases: ['cemento', 'cemento portland', 'tipos de cemento'], definition: 'El cemento es el conglomerante hidráulico que, mezclado con agua, forma una pasta que endurece y aglutina los agregados en el concreto. Existen tipos CPC, CPO, CPP y otros con resistencias y resistencias químicas distintas.', practical: 'Debe almacenarse seco, en lotes identificados y usarse dentro de su vigencia; cemento endurecido o húmedo compromete resistencias por más dosificación que se haga en obra.', courses: ['Supervisión Integral', 'Trabes AASHTO'] },
      mortero: { label: 'Mortero', aliases: ['mortero', 'morteros', 'junteado', 'mezcla de albañileria'], definition: 'El mortero es una mezcla de cemento, cal, arena y agua usada para pegar piezas de mampostería, aplanar muros y nivelar superficies. Su proporción define resistencia y trabajabilidad.', practical: 'La relación agua-cemento, la arena limpia y la mezcla continua son clave. Un mortero mal dosificado se desprende, agrieta o pierde adherencia con el block.', courses: ['Supervisión Integral', 'Residente de Obra'] },
      agregados: { label: 'Agregados pétreos', aliases: ['agregados', 'grava y arena', 'agregados petreos'], definition: 'Los agregados son los materiales inertes (grava, arena, piedra triturada) que componen la mayor parte del volumen del concreto. Su granulometría, limpieza y forma afectan directamente la resistencia y durabilidad.', practical: 'Deben cumplir normas de granulometría, estar libres de materia orgánica y arcilla, y almacenarse separados. Comprar por precio sin verificar calidad produce concretos débiles aunque la dosificación sea correcta.', courses: ['Supervisión Integral', 'Trabes AASHTO'] },
      aditivos: { label: 'Aditivos para concreto', aliases: ['aditivo', 'aditivos', 'aditivos para concreto', 'plastificante', 'acelerante', 'retardante'], definition: 'Los aditivos modifican propiedades del concreto fresco o endurecido: trabajabilidad, tiempo de fraguado, resistencia inicial, impermeabilidad o resistencia química.', practical: 'Deben dosificarse por ficha técnica y pruebas, no por costumbre. Mezclar dos aditivos incompatibles o aplicar sobredosis puede reducir resistencia, generar segregación o acelerar el fraguado peligrosamente.', courses: ['Supervisión Integral', 'Trabes AASHTO'] },
      impermeabilizacion: { label: 'Impermeabilización', aliases: ['impermeabilizacion', 'impermeabilizar', 'impermeable', 'sellado de humedad'], definition: 'La impermeabilización protege elementos constructivos de la humedad y el agua: azoteas, cisternas, cimentaciones, baños y muros expuestos.', practical: 'Un sistema efectivo integra pendientes, chaflanes, membranas, protección mecánica y mantenimiento. Impermeabilizar sin corregir fugas, cuarteaduras o pendientes es gastar en un sistema que fallará.', courses: ['Supervisión Integral', 'Residente de Obra'] },
      'junta-constructiva': { label: 'Juntas constructivas', aliases: ['junta constructiva', 'juntas constructivas', 'junta de colado', 'junta fria'], definition: 'Las juntas constructivas son interrupciones intencionales del colado que permiten controlar la secuencia de trabajo, el curado y las deformaciones del concreto.', practical: 'Deben ubicarse donde el diseño lo permite, prepararse con limpieza y rugosidad, y continuarse con un concreto compatible. Juntas mal preparadas crean puntos débiles ante cortante y filtración.', courses: ['Supervisión Integral', 'Trabes AASHTO'] },
      'perfil-estructural': { label: 'Perfiles de acero estructural', aliases: ['perfil estructural', 'perfiles estructurales', 'acero estructural', 'ipr', 'ptr', 'canal estructural'], definition: 'Los perfiles de acero estructural (IPR, IPS, PTR, ángulos, canales) se emplean en estructuras metálicas, naves industriales, entrepisos ligeros y refuerzos.', practical: 'Requieren verificación de calidad, dimensiones, condiciones de almacenamiento y protección anticorrosiva. Las conexiones son el punto crítico: una soldadura o tornillería deficiente anula la capacidad del perfil.', courses: ['Supervisión Integral', 'Trabes AASHTO'] },
      soldadura: { label: 'Soldadura estructural', aliases: ['soldadura', 'soldadura estructural', 'uniones soldadas'], definition: 'La soldadura une elementos de acero mediante fusión. Su calidad depende del procedimiento calificado, soldador certificado, materiales de aporte, posición y preparación de bordes.', practical: 'Debe inspeccionarse visualmente y, cuando aplica, con ensayos no destructivos. Soldaduras improvisadas, con porosidades o faltas de fusión comprometen conexiones críticas aunque luzcan uniformes.', courses: ['Supervisión Integral', 'Trabes AASHTO'] },
      zapata: { label: 'Zapatas', aliases: ['zapata', 'zapatas', 'zapata aislada', 'zapata corrida', 'zapata combinada'], definition: 'Las zapatas son cimentaciones superficiales que distribuyen la carga de columnas o muros sobre un área mayor del terreno. Pueden ser aisladas, corridas, combinadas o conectadas por contratrabes.', practical: 'Dependen del estudio de suelos, cargas, nivel de desplante y refuerzo. Modificar dimensiones o reducir refuerzo sin análisis es una causa frecuente de asentamientos diferenciales.', courses: ['Supervisión Integral', 'Trabes AASHTO'] },
      pilote: { label: 'Pilotes y pilas', aliases: ['pilote', 'pilotes', 'pilas', 'cimentacion profunda'], definition: 'Pilotes y pilas son elementos de cimentación profunda que transmiten la carga a estratos resistentes cuando el suelo superficial no es adecuado. Pueden ser hincados, perforados, pretensados o colados in situ.', practical: 'Su diseño y ejecución exigen estudios geotécnicos robustos, control de verticalidad, carga y pruebas; errores en cimentación profunda son los más costosos de corregir.', courses: ['Supervisión Integral', 'Trabes AASHTO'] },
      losa: { label: 'Losas', aliases: ['losa', 'losas', 'losa maciza', 'losa aligerada', 'entrepiso'], definition: 'Las losas son elementos planos que soportan cargas gravitacionales y las transmiten a vigas, muros o columnas. Pueden ser macizas, aligeradas, nervadas, reticulares o colaborantes.', practical: 'Su diseño integra claros, cargas, deflexiones, acero y recubrimientos. En obra se verifican espesores, armado, apuntalamientos y colado continuo sin juntas no previstas.', courses: ['Supervisión Integral', 'Trabes AASHTO'] },
      columna: { label: 'Columnas', aliases: ['columna', 'columnas', 'elemento vertical estructural'], definition: 'Las columnas son elementos verticales que transmiten cargas de losas y vigas a la cimentación, resistiendo compresión, flexocompresión y, en algunos casos, torsión.', practical: 'La geometría, refuerzo longitudinal, estribos de confinamiento y recubrimientos son críticos para resistencia sísmica. Reducir estribos en zonas de confinamiento es una falla grave recurrente.', courses: ['Supervisión Integral', 'Trabes AASHTO'] },
      viga: { label: 'Vigas y trabes', aliases: ['viga', 'vigas', 'trabe', 'trabes'], definition: 'Vigas y trabes son elementos horizontales que soportan losas y transmiten cargas a las columnas o muros. Resisten flexión, cortante y a veces torsión.', practical: 'Se verifican geometría, estribos (especialmente en zonas de confinamiento), traslapes, recubrimientos y continuidad del acero. Perforar una trabe sin análisis es una práctica peligrosa habitual.', courses: ['Trabes AASHTO', 'Supervisión Integral'] },
      pavimento: { label: 'Pavimentos y carpetas', aliases: ['pavimento', 'carpeta asfaltica', 'pavimento rigido', 'pavimento flexible', 'base y subbase'], definition: 'Los pavimentos distribuyen cargas vehiculares sobre el terreno. Los flexibles usan carpeta asfáltica sobre base y subbase; los rígidos usan losas de concreto hidráulico.', practical: 'La durabilidad depende más del diseño de las capas inferiores y del drenaje que del espesor visible. Un pavimento sobre base mal compactada se agrieta y bachea rápidamente.', courses: ['Supervisión Integral', 'Trabes AASHTO'] },

      'instalacion-hidraulica': { label: 'Instalación hidráulica', aliases: ['instalacion hidraulica', 'instalaciones hidraulicas', 'tuberia de agua', 'red de agua potable'], definition: 'La instalación hidráulica suministra agua potable fría y caliente a los muebles sanitarios y equipos. Comprende toma, cisterna, bombeo, tuberías, válvulas, calentadores y controles.', practical: 'Su diseño considera demanda simultánea, presiones, materiales, pendientes y protección. Pruebas de hermeticidad antes de aplanar o cubrir evitan rupturas invisibles costosas de corregir después.', courses: ['Supervisión Integral', 'Residente de Obra'] },
      'instalacion-sanitaria': { label: 'Instalación sanitaria', aliases: ['instalacion sanitaria', 'drenaje sanitario', 'drenaje pluvial', 'red sanitaria'], definition: 'La instalación sanitaria desaloja aguas residuales y pluviales mediante tuberías, pendientes, registros, trampas y ventilaciones, hasta la red municipal o planta de tratamiento.', practical: 'Pendientes correctas, ventilaciones, trampas y registros accesibles son esenciales. Juntar aguas negras y pluviales en un municipio con red separada acarrea sanciones y problemas operativos.', courses: ['Supervisión Integral', 'Residente de Obra'] },
      'instalacion-electrica': { label: 'Instalación eléctrica', aliases: ['instalacion electrica', 'instalaciones electricas', 'cfe', 'tablero electrico'], definition: 'La instalación eléctrica distribuye energía desde la acometida hasta cada receptáculo con conductores, protecciones, tableros, canalizaciones y tierras físicas conforme a NOM-001-SEDE.', practical: 'Debe diseñarse por un responsable, usar materiales certificados, respetar calibres, protecciones diferenciales y tierras físicas. Pruebas y memoria son obligatorias para dictamen de verificación.', courses: ['Supervisión Integral', 'Residente de Obra'] },
      'instalacion-gas': { label: 'Instalación de gas LP y natural', aliases: ['instalacion de gas', 'gas lp', 'gas natural', 'nom gas'], definition: 'La instalación de gas conduce combustible desde el tanque o acometida hasta los aparatos, considerando materiales compatibles, ventilaciones, válvulas, pruebas de hermeticidad y dictámenes.', practical: 'Requiere unidad de verificación autorizada en instalaciones que lo exijan y materiales certificados. Una fuga de gas por mala soldadura o manguera inadecuada es un riesgo de siniestro mayor.', courses: ['Supervisión Integral', 'Residente de Obra'] },
      cfe: { label: 'Trámite CFE', aliases: ['cfe', 'tramite cfe', 'contrato cfe', 'medidor cfe'], definition: 'El trámite ante CFE formaliza el suministro eléctrico: solicitud, factibilidad, acometida, medidor y contrato, con requisitos distintos según carga, tensión y tipo de servicio.', practical: 'Debe iniciarse al proyectar la obra con dictamen de unidad verificadora y diagramas; dejarlo al final retrasa entrega y provoca costos de ajustes.', courses: ['Gerencia de Proyectos', 'Residente de Obra'] },
      conagua: { label: 'Trámites CONAGUA', aliases: ['conagua', 'descarga de agua', 'concesion de agua', 'pozo profundo'], definition: 'CONAGUA regula uso, aprovechamiento y descarga de aguas nacionales. Perforación de pozos, descargas y uso industrial requieren títulos, permisos y reportes periódicos.', practical: 'Operar sin permisos o sin cumplir límites de descarga puede derivar en multas y clausura; un proyecto grande requiere este trámite desde la planeación, no al final.', courses: ['Gerencia de Proyectos', 'Contratos en la Construcción'] },

      acabados: { label: 'Acabados', aliases: ['acabados', 'acabado interior', 'acabado exterior', 'acabados arquitectonicos'], definition: 'Los acabados son la capa final de muros, pisos, plafones, fachadas y mobiliario fijo. Dan carácter al proyecto, protegen la obra base y suelen concentrar un porcentaje importante del presupuesto.', practical: 'Un buen acabado inicia con sustratos planos, limpios y estables; una pintura o un piso cerámico sobre un soporte mal preparado falla aunque el material sea de alta gama.', courses: ['Elaboración de Láminas', 'Supervisión Integral'] },
      albañileria: { label: 'Albañilería', aliases: ['albañileria', 'albanileria', 'muros de obra', 'trabajos de albañileria'], definition: 'La albañilería agrupa trabajos de muros, aplanados, dalas, castillos, chaflanes, instalaciones ocultas y resanes. Es la base sobre la cual se montan los acabados.', practical: 'Verifica aplomo, nivel, cuatropeos, dentados, refuerzos y curado. Un muro mal ejecutado se compensa con aplanados gruesos que agrietan a los pocos meses.', courses: ['Supervisión Integral', 'Residente de Obra'] },
      yesos: { label: 'Yeso y pastas', aliases: ['yeso', 'pastas', 'aplanado de yeso', 'estuco', 'tabla roca'], definition: 'Yeso y pastas proporcionan superficies lisas listas para pintar. Pueden aplicarse como aplanado tradicional, pastas acrílicas o sistemas de panel de yeso con tratamiento de juntas.', practical: 'La superficie base debe estar firme, limpia y seca. Yeso sobre humedad activa o sobre losa sin resane adecuado se desprende en poco tiempo.', courses: ['Supervisión Integral', 'Residente de Obra'] },
      pisos: { label: 'Pisos y recubrimientos', aliases: ['piso', 'pisos', 'piso ceramico', 'porcelanato', 'piso de madera', 'piso vinilico'], definition: 'Los pisos recubren la superficie horizontal transitable. Pueden ser cerámicos, porcelánicos, pétreos, de madera, vinílicos, pulidos o continuos; cada uno con requisitos de sustrato y mantenimiento.', practical: 'Define primero el uso (tránsito, humedad, química), después el acabado. Instalar un piso bonito sobre un sustrato con humedad o movimiento provoca despegues y agrietamientos.', courses: ['Elaboración de Láminas', 'Supervisión Integral'] },
      pintura: { label: 'Pintura', aliases: ['pintura', 'pintar muros', 'pintura vinilica', 'pintura esmalte', 'pintura exterior'], definition: 'La pintura protege y da color a superficies. Existen vinílicas, esmaltes, epóxicas, texturizadas y recubrimientos especializados según exposición, sustrato y uso.', practical: 'Preparar el sustrato (limpieza, sellado, resanes) suele ser más determinante que la marca. Pintar sobre humedad, polvo o sales produce fallas pronto, visibles como pelado o manchas.', courses: ['Elaboración de Láminas', 'Supervisión Integral'] },
      carpinteria: { label: 'Carpintería arquitectónica', aliases: ['carpinteria', 'carpinteria arquitectonica', 'muebles de obra', 'closets'], definition: 'La carpintería arquitectónica integra puertas, closets, cocinas, mamparas y muebles de obra, con herrajes, acabados y conexiones a instalaciones.', practical: 'Requiere planos de taller, mediciones en obra, previsión de instalaciones, selección de herrajes y acabados compatibles con uso y humedad. Comprar sin planos de taller es garantía de reprocesos.', courses: ['Elaboración de Láminas', 'SketchUp Profesional'] },
      herreria: { label: 'Herrería', aliases: ['herreria', 'estructura metalica ligera', 'protecciones metalicas'], definition: 'La herrería agrupa estructuras metálicas ligeras: barandales, rejas, pasamanos, protecciones, escaleras y pérgolas, generalmente en acero al carbono.', practical: 'Define cargas, acabados anticorrosivos, soldaduras, sujeciones y tolerancias. Herrería atornillada a muros sin anclajes adecuados puede fallar al primer esfuerzo real.', courses: ['Elaboración de Láminas', 'Supervisión Integral'] },
      canceleria: { label: 'Cancelería y ventanería', aliases: ['canceleria', 'ventaneria', 'aluminio canceleria', 'ventanas de pvc'], definition: 'La cancelería y ventanería forman la envolvente ligera: ventanas, puertas corredizas, muros vidriados y domos, con perfiles de aluminio, acero o PVC.', practical: 'Deben considerarse pesos, cristales con espesores correctos, hermeticidad, ventilación de perfiles, selladores compatibles y sistemas de drenaje interno. Fallas típicas: filtraciones por sellado deficiente.', courses: ['Elaboración de Láminas', 'Supervisión Integral'] },
      plafones: { label: 'Plafones y falsos techos', aliases: ['plafon', 'plafones', 'falso plafon', 'cielo raso', 'tablaroca de plafon'], definition: 'Los plafones son techos secundarios suspendidos del elemento estructural que ocultan instalaciones y permiten iluminación, acústica o accesos de servicio.', practical: 'Deben soportar su propio peso, equipos luminarios y registros de servicio con cuelgues bien anclados. Un plafón con cuelgues insuficientes se descuelga parcialmente y se nota de inmediato.', courses: ['Supervisión Integral', 'Elaboración de Láminas'] }
    }
  });
})();
